CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities (
	id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY,
	state_id INT NOT NULL, 
	CONSTRAINT fk_state_id
	FOREIGN KEY (id) REFERENCES hbtn_0d_usa.states(id)
	ON RESTRIC CASCADE,
	name VARCHAR(256) NOT NULL
);
